language: python

python:
    - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https

# install - install any dependencies required
install:
    - gem install asciidoctor
    # install latest release version
    - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
    - sudo dpkg -i hugo*.deb
    - rm -rf public 2> /dev/null

script:
  - hugo version
  - hugo -v

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master

notifications:
  slack:
    secure: $SLACK_TOKEN
